# Add C++ sources whose definitions are shared between host C++ and CUDA device
# code.
#
# The matching header declares the functions with IPC_TOOLKIT_HOST_DEVICE and
# does NOT textually include the .cpp, so editing a definition rebuilds a single
# translation unit plus a link step instead of every TU that includes the
# header.
#
# Without CUDA each .cpp is compiled normally. With CUDA each .cpp must be
# compiled as a genuine .cu so nvcc emits *relocatable* device code that other
# TUs can device-link against. Setting LANGUAGE CUDA on a .cpp is not enough:
# CMake's separable-compilation and device-link bookkeeping key off the .cu
# extension, so the .cpp gets a host symbol but no linkable __device__ symbol.
# For each .cpp this function generates a one-line .cu wrapper in the build tree
# (so nothing extra is committed) and adds it to the target instead.
#
# Usage:
#   ipc_toolkit_target_shared_device_sources(ipc_toolkit
#     point_point.cpp
#     distance_type.cpp
#     ...)
function(ipc_toolkit_target_shared_device_sources target)
  set(sources_to_add "")
  foreach(src IN LISTS ARGN)
    if(IPC_TOOLKIT_WITH_CUDA)
      get_filename_component(src_abs "${src}" ABSOLUTE
        BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")

      # Mirror the source's path (relative to the current source dir) under the
      # wrapper directory so that duplicate base names in different subfolders
      # (e.g. a/point.cpp and b/point.cpp) get distinct wrapper paths instead of
      # colliding on a single flattened name.
      file(RELATIVE_PATH src_rel "${CMAKE_CURRENT_SOURCE_DIR}" "${src_abs}")
      get_filename_component(rel_dir "${src_rel}" DIRECTORY)
      get_filename_component(src_name_we "${src_rel}" NAME_WE)

      set(wrapper_dir "${CMAKE_CURRENT_BINARY_DIR}/cuda_device_wrappers")
      if(rel_dir)
        set(wrapper_dir "${wrapper_dir}/${rel_dir}")
      endif()
      set(wrapper "${wrapper_dir}/${src_name_we}.cu")

      # file(GENERATE) only rewrites when the content changes, so this does not
      # trigger spurious rebuilds on reconfigure. The wrapper #includes the
      # original .cpp by absolute path; the compiler's dependency scan then ties
      # the wrapper TU to the .cpp, so editing the .cpp rebuilds just this TU.
      file(GENERATE OUTPUT "${wrapper}" CONTENT
"// Generated by ipc_toolkit_target_shared_device_sources() -- do not edit.
// Compiles ${src_rel} as a CUDA translation unit so nvcc emits relocatable
// device code linkable from other TUs. Edit the .cpp instead.
#include \"${src_abs}\"
")

      set_source_files_properties("${wrapper}" PROPERTIES GENERATED TRUE)
      list(APPEND sources_to_add "${wrapper}")
    else()
      list(APPEND sources_to_add "${src}")
    endif()
  endforeach()

  target_sources(${target} PRIVATE ${sources_to_add})
endfunction()
