name: Other
description: Ask a question or request a new feature
body:
  - type: markdown
    attributes:
      value: |
        ## Important information
        For all types of questions, feature requests, and other issues that are not bugs, please start a post on the separate "Discussions" tab and **not** under "Issues".

        If have found a bug, then please open an issue with a reproducer using the separate "Bug Report" template.

  - type: textarea
    id: description
    attributes:
      label: Please don't use.
      placeholder: |
        For all types of questions, feature requests, and other issues that are not bugs, please start a post on the separate "Discussions" tab and **not** under "Issues".

        If have found a bug, then please open an issue with a reproducer using the separate "Bug Report" template.

    validations:
      required: true
