name: clang-format Check
on:
  push:
  pull_request:
    paths:
      - '.github/workflows/clang-format-check.yml'
      - '.clang-format'
      - 'src/**'
      - 'tests/src/**'
      - 'python/src/**'
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src'
          - 'tests/src'
          - 'python/src'
    steps:
    - uses: actions/checkout@v4
    - name: clang-format style check
      uses: jidicula/clang-format-action@v4.13.0
      with:
        clang-format-version: '17'
        check-path: ${{ matrix.path }}